# Generated by Django 5.2.4 on 2025-07-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0010_journal_approved_journal_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('submitted_by', models.CharField(max_length=100)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='site_expenses/')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.constructionsite')),
            ],
        ),
    ]
