# Generated by Django 5.2.4 on 2025-07-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SiteExpense', '0001_initial'),
        ('accounting', '0010_journal_approved_journal_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('approved', models.BooleanField(default=False)),
                ('created_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('accounts_payable_account', models.ForeignKey(blank=True, help_text='Default: Accounts Payable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_as_ap', to='accounting.account')),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='accounting.journal')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.constructionsite')),
                ('site_expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='SiteExpense.siteexpense')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.purchase')),
            ],
        ),
    ]
