# Generated by Django 5.2.4 on 2025-07-05 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_journal_approved_journal_approved_at_and_more'),
        ('purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseline',
            old_name='amount',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='purchaseline',
            name='account',
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseline',
            name='description',
            field=models.CharField(help_text='Editable description for this specific purchase.', max_length=255),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('material', 'Material'), ('service', 'Service')], default='material', max_length=20)),
                ('unit_of_measure', models.CharField(blank=True, help_text='e.g., kg, hour, piece', max_length=50)),
                ('expense_account', models.ForeignKey(help_text='Default expense account for this item.', on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='purchase.item'),
            preserve_default=False,
        ),
    ]
