# Generated by Django 5.2.4 on 2025-07-05 18:03

from django.db import migrations


def create_demo_items(apps, schema_editor):
    """Creates demo data for the Item model."""
    Item = apps.get_model('purchase', 'Item')
    Account = apps.get_model('accounting', 'Account')

    # Get or create expense accounts to associate with items
    materials_account, _ = Account.objects.get_or_create(
        name='Site Materials',
        defaults={
            'account_code': '6100',
            'type': 'expense',
        }
    )
    subcontractor_account, _ = Account.objects.get_or_create(
        name='Subcontractor Expenses',
        defaults={
            'account_code': '6200',
            'type': 'expense',
        }
    )
    equipment_account, _ = Account.objects.get_or_create(
        name='Equipment Rental',
        defaults={
            'account_code': '6300',
            'type': 'expense',
        }
    )

    items_data = [
        {'name': 'Cement Bag (50kg)', 'description': 'Standard Portland Cement, 50kg bag.', 'expense_account': materials_account},
        {'name': 'Rebar (10mm, 6m)', 'description': '10mm deformed steel reinforcement bar, 6-meter length.', 'expense_account': materials_account},
        {'name': 'Plywood Sheet (4x8)', 'description': 'Standard 4x8 feet plywood sheet for formwork.', 'expense_account': materials_account},
        {'name': 'Electrical Wiring (per meter)', 'description': 'Standard 2.5mm copper electrical wire.', 'expense_account': subcontractor_account},
        {'name': 'Excavator Rental (per hour)', 'description': 'Rental of a 20-ton excavator with operator.', 'expense_account': equipment_account},
        {'name': 'Plumbing Services (per hour)', 'description': 'Standard plumbing labor for installation.', 'expense_account': subcontractor_account},
    ]

    for item_data in items_data:
        Item.objects.create(**item_data)

def delete_demo_items(apps, schema_editor):
    """Deletes the demo items created in create_demo_items."""
    Item = apps.get_model('purchase', 'Item')
    item_names = [
        'Cement Bag (50kg)',
        'Rebar (10mm, 6m)',
        'Plywood Sheet (4x8)',
        'Electrical Wiring (per meter)',
        'Excavator Rental (per hour)',
        'Plumbing Services (per hour)',
    ]
    Item.objects.filter(name__in=item_names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_rename_amount_purchaseline_unit_price_and_more'),
        # Add dependency on the accounting migration that creates standard accounts
        ('accounting', '0003_standard_accounts'),
    ]

    operations = [
        migrations.RunPython(create_demo_items, reverse_code=delete_demo_items),
    ]
