# Generated by Django 5.2.4 on 2025-07-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_standard_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
