# Generated by Django 5.2.4 on 2025-07-03 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_transaction_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalcontribution',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capital_contributions', to='accounting.transaction'),
        ),
    ]
