# Generated by Django 5.2.4 on 2025-07-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_rename_entry_transactionentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Journal',
        ),
        migrations.RenameModel(
            old_name='TransactionEntry',
            new_name='JournalEntry',
        ),
        migrations.RenameField(
            model_name='capitalcontribution',
            old_name='transaction',
            new_name='journal',
        ),
        migrations.RenameField(
            model_name='journalentry',
            old_name='transaction',
            new_name='journal',
        ),
    ]
