# Generated by Django 5.2.4 on 2025-07-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_rename_transaction_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='journal_type',
            field=models.CharField(choices=[('general', 'General'), ('cash_receipts', 'Cash Receipts'), ('cash_payments', 'Cash Payments'), ('sales', 'Sales'), ('purchases', 'Purchases'), ('bank', 'Bank'), ('petty_cash', 'Petty Cash'), ('payroll', 'Payroll'), ('capital', 'Capital'), ('adjustment', 'Adjustment')], default='general', max_length=20),
        ),
    ]
